---
- block:
  - name: check if certs need to be generated
    shell: "stat {{taskd_certs_path}}/*.pem"
    register: certs_state
    ignore_errors: yes

  - fail:
      msg: "certificates exist already"
    when: certs_state.rc == 0

  - name: create certs directory
    file:
      path: "{{taskd_certs_path}}"
      state: directory
    become: true
    become_user: "{{taskd_user}}"

  - name: copy vars file
    template:
      src: vars
      dest: "{{taskd_certs_path}}/vars"

  - name: generate certificates
    shell: "{{taskd_source_dir}}/pki/{{item}}"
    args:
      chdir: "{{taskd_certs_path}}"
    with_items:
      - generate.ca
      - generate.server
      - generate.crl
    become: true
    become_user: "{{taskd_user}}"
    notify:
    - restart taskd

  rescue:

  - debug:
      msg: "proceed"
